services:
  bot:
    image: 21id-bot:latest
    container_name: bot
    restart: unless-stopped
    environment:
      BOTAPI_TOKEN: ${BOTAPI_TOKEN}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOSTS: ${MONGO_HOSTS}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      S21API_LOGIN: ${S21API_LOGIN}
      S21API_PASSWORD: ${S21API_PASSWORD}
      S21API_BASE_URL: ${S21API_BASE_URL}
      S21API_AUTH_URL: ${S21API_AUTH_URL}
      S21API_AUTH_REALM: ${S21API_AUTH_REALM}
      TEMPLATES_BASEDIR: ${TEMPLATES_BASEDIR}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local